### PR TITLE
adding _repr_svg_ to Source

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
I extended Source class to possess _repr_svg_ method.
Now it can be rendered in Jupyter Notebooks like Dot or Digraph class.

### CODE REVIEW

**Comment by xflr6** [comment]
Great idea.

Can you replace both `repr_svg`s of `Dot` and `Source` by a single one up in `File` (maybe below `__init__`) to make it more DRY?

**Comment by RafalSkolasinski** [comment]
Sure, will do.

**Comment by RafalSkolasinski** [comment]
Should be fine now.

**Comment by RafalSkolasinski** [comment]
Great :)

**Comment by xflr6** [comment]
Thanks, new release will follow.

**Pull request merged**
