### PR TITLE
Add documentation notes/tips on redefining nodes/edges (was: extend rank_same.py example)

### PR DESCRIPTION
**Pull request by BMaxV**
Hi!

This is the answer to a question I had and had to look up on how to do it. So that's the motivation and reason for the PR.

I didn't see any contribution guidelines, so if there is something wrong let's talk.

Also thank you so much for the module, it's a great help!

### CODE REVIEW

**Comment by xflr6** [comment]
Thanks for the PR.

Let's not add nodes to [examples/rank_same.py](https://github.com/xflr6/graphviz/blob/master/examples/rank_same.py): it reproduces the graph from the [linked SO question](https://stackoverflow.com/questions/25734244/how-do-i-place-nodes-on-the-same-level-in-dot) (line 2).

IIUC, this is about documenting that the following two are equivalent:

```python
import graphviz

d = graphviz.Digraph()

with d.subgraph() as s:
    s.attr(rank='same')
    s.node('1', 'hello')
    s.node('3', 'there')

d.node('2', 'world')

d.edges(['13', '32'])
```

spam

```python
import graphviz

d = graphviz.Digraph()

d.node('1', 'hello')
d.node('2', 'world')
d.node('3', 'there')

with d.subgraph() as s:
    s.attr(rank='same')
    s.node('1')
    s.node('3')

d.edges(['13', '32'])
```

(renders the same graph)

Can you maybe clarify why one would prefer the second over the first?

If this seems underdocumented, would it make sense to try and get it documented [upstream](https://graphviz.org/documentation/) (all [Graphviz](https://www.graphviz.org/) users vs. only users of the Python `graphviz` library here)?

Not completely convinced that this is needed, but if so: How about adding a note to the [Subgraphs & clusters section](https://graphviz.readthedocs.io/en/stable/manual.html#subgraphs-clusters) clarifying that they can be used to control the placement of nodes that are defined outside of them (with a short example)?

nit: Please format code consistent with the present style/conventions (e.g. string literals, comments; basic [pep8](https://www.python.org/dev/peps/pep-0008/)).

**Comment by BMaxV** [comment]
Hi,

> Can you maybe clarify why one would prefer the second over the first?

Sure, my use case problem/question was that the graph was already defined and I wondered if I had to change how the graph is defined or if I can just append the rank info. It can just be appended, nodes aren't overwritten by redefining them in the subgraph, but instead the information about rank is updated and added to the original. That wasn't obvious to me.

So the two variations produce the same output but are different approaches with different advantages.

I am not sure how to show that with just the original file/graph, since it's not as obvious when the id string is reused as node text. Should I move it to a different file?

And yes, I forgot to run the autopep8, I will do that.

Thanks for the super quick response time and feedback!

**Comment by xflr6** [comment]
>  It can just be appended, nodes aren't overwritten by redefining them in the subgraph, but instead the information about rank is updated and added to the original. That wasn't obvious to me.

I see. I think this might be at least related to the more general point that repeated `node` statements update the nodes  properties:

```python
import graphviz

d = graphviz.Digraph(strict=True)

d.node('spam')
d.node('spam', label='eggs')
d
```
spam

The same holds for `edge` statements with `strict=True` graphs (i.e. no double edges):

```python
import graphviz

d = graphviz.Digraph(strict=True)

d.edge('spam', 'eggs')
d.edge('spam', 'eggs', arrowhead='vee')
d
```
spam

Similarly, `subgraph` with `rank=` can apparently (also) be used to set the group attribute *later*.

Another related point might be that one can also do completely without `node` statements and only use `edge` statements as long as one does not need to set attributes on the nodes (or one can add the `edge` statements first).

> Should I move it to a different file?

I am thinking about adding a section to [the end of the documentation](https://graphviz.readthedocs.io/en/stable/manual.html) with some code examples such as the ones above to provide some guidance? I would consider this 'tips & tricks' like advice. WDYT?

>> would it make sense to try and get it documented upstream

> No, it's not an upstream problem because in the .gv source file it's more obvious that this is possible and valid

In my understanding, this library is precisely for assembling DOT source code programmatically, i.e. not to build a object-oriented represenation of a graph to be rendered. I think there might be a slight misconception here, e.g. `d.node("A")` is *not* a constructor but a method for appending a `node` statement to `d`. What that statement means/does is completely defined by how the upstream renderer ([Graphviz](www.graphviz.org/)) interprets it (there is no further abstraction, it is *transparent*). If the API would be about creating an object-oriented representation of the graph, I think one would e.g. expect the method to return a node instance object or there being ways to retrieve and update node and edge objects that have been defined previously. Does that make sense?

**Comment by BMaxV** [comment]
Hi

>I am thinking about adding a section to the end of the documentation with some code examples such as the ones above to provide some guidance. I would consider this 'tips & tricks' like advice. WDYT?

I would put it at the end of "basic usage" or in the "attributes" section.

Reusing your example, I would put two attributes like this in the definition to make it obvious that 'star' isn't being overwritten by 'eggs'.

```
import graphviz

d = graphviz.Digraph(strict=True)

d.node('spam')
d.node('spam', shape='star')
d.node('spam', label='eggs')
```

>In my understanding, this library is precisely for assembling DOT source code programmatically. [...] Does that make sense?

Yes, I do think it deserves a mention in the manual though. For example matplotlib does it in a way that you don't have to specify objects for plotting to work, but it still creates them. Not creating objects works too, but it wasn't the approach I expected.

**Comment by xflr6** [comment]
Closing stale PR for now. Please update and re-open if there is still interest in extending the documentation here.

**Pull request closed without merging**
