### PR TITLE
Document port and compass encoding in edge() method

### PR DESCRIPTION
**Pull request by mgoral**
Documentation of current colon-splitting behaviour for issue #53

### CODE REVIEW

**Comment by xflr6** [comment]
Thanks.

**Comment by xflr6** [comment]
Changed the wording of the new documentation in c07b08b04ceb05feef7dcf117538810af85088e6: please tell me in case you prefer not to be credited in the changelog

**Comment by mgoral** [comment]
I'm OK with it, thanks :-)

13 lip 2020 13:14:36 Sebastian Bank <notifications@github.com>:

**Comment by xflr6** [comment]
Thanks, released [https://pypi.org/project/graphviz/0.14.1/#files](0.14.1) (435030543a9e8aa31b9667b400cf76b40829df0a)

**Pull request merged**
