### PR TITLE
Add Python 2.6 compatibility

### PR DESCRIPTION
**Pull request by jcrist**
Note that this adds unittest2 as a test dependency.

### CODE REVIEW

**Comment by xflr6** [comment]
Thanks for your effort. Do you see conrete demand for 2.6 support (AFAIR 2.6 should have very little users)? What would be the time to drop 2.6 support?

**Comment by jcrist** [comment]
I work on http://dask.pydata.org/en/latest/, which supports python 2.6. I'd like to move from pydot to your package, as I like the interface more, and it supports python 3. I'm not sure who's still using python 2.6, but the changes to support it are fairly small.

**Comment by jcrist** [comment]
Thanks for merging and pushing a release! I look forward to using this.

**Comment by TApplencourt** [comment]
I use some old supercomputer with only python 2.6 available...  So, many  thanks for this compatibility !

**Pull request merged**
